import type { Course } from '../types/course'

const courses: Course[] = [
  {
    id: 1,
    code: 'CS201',
    name: 'Algoritmos',
    professor: 'Perez',
    rating: 4.5,
    reviewsCount: 62,
    studentsCount: 130,
  },
  {
    id: 2,
    code: 'CS210',
    name: 'Base de Datos',
    professor: 'Gomez',
    rating: 4.2,
    reviewsCount: 54,
    studentsCount: 118,
  },
  {
    id: 3,
    code: 'CS330',
    name: 'Cloud Computing',
    professor: 'Rojas',
    rating: 4.8,
    reviewsCount: 77,
    studentsCount: 146,
  },
  {
    id: 4,
    code: 'CS115',
    name: 'Programacion I',
    professor: 'Mendoza',
    rating: 4.1,
    reviewsCount: 88,
    studentsCount: 180,
  },
  {
    id: 5,
    code: 'CS220',
    name: 'Estructuras de Datos',
    professor: 'Quispe',
    rating: 4.6,
    reviewsCount: 69,
    studentsCount: 139,
  },
  {
    id: 6,
    code: 'CS410',
    name: 'Inteligencia Artificial',
    professor: 'Salazar',
    rating: 4.7,
    reviewsCount: 73,
    studentsCount: 121,
  },
  {
    id: 7,
    code: 'CS405',
    name: 'Ingenieria de Software',
    professor: 'Torres',
    rating: 4.3,
    reviewsCount: 65,
    studentsCount: 127,
  },
  {
    id: 8,
    code: 'CS225',
    name: 'Redes de Computadoras',
    professor: 'Valdivia',
    rating: 3.9,
    reviewsCount: 39,
    studentsCount: 104,
  },
  {
    id: 9,
    code: 'CS430',
    name: 'Mineria de Datos',
    professor: 'Ramos',
    rating: 4.4,
    reviewsCount: 44,
    studentsCount: 92,
  },
  {
    id: 10,
    code: 'CS310',
    name: 'Sistemas Operativos',
    professor: 'Luna',
    rating: 4,
    reviewsCount: 58,
    studentsCount: 132,
  },
  {
    id: 11,
    code: 'CS240',
    name: 'Matematica Discreta',
    professor: 'Castillo',
    rating: 4.1,
    reviewsCount: 47,
    studentsCount: 116,
  },
  {
    id: 12,
    code: 'CS450',
    name: 'Seguridad Informatica',
    professor: 'Paredes',
    rating: 4.6,
    reviewsCount: 51,
    studentsCount: 97,
  },
]

const getCourses = () => courses

const getCourseById = (id: number) => courses.find((course) => course.id === id)

export const courseService = {
  getCourseById,
  getCourses,
}
